- name: Deploy Jenkins in Kubernetes
  hosts: k3s_1st_master_install
  remote_user: root
  gather_facts: true

  tasks:

    - name: Deploy Jenkins
      securityContext:
        fsGroup: 1000 
        runAsUser: 0
      shell: |
        kubectl create namespace jenkins
        kubectl apply -f https://raw.githubusercontent.com/jartas/DevOps/main/App/jenkins/jenkins_pvc.yaml --kubeconfig /etc/rancher/k3s/k3s.yaml -n jenkins
        kubectl apply -f https://raw.githubusercontent.com/jartas/DevOps/main/App/jenkins/jenkins-deployment.yaml --kubeconfig /etc/rancher/k3s/k3s.yaml -n jenkins
        kubectl apply -f https://raw.githubusercontent.com/jartas/DevOps/main/App/jenkins/jenkins-service.yaml --kubeconfig /etc/rancher/k3s/k3s.yaml -n jenkins
      args:
        executable: /bin/bash