apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: postgres-app
  name: postgres-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-app
  template:
    metadata:
      labels:
        app: postgres-app
    spec:
      containers:
      - image: postgres:15-alpine
        name: postgres-app
        envFrom:
        - configMapRef:
            name: configmap-db
        ports:
        - containerPort: 5432
          name: postgres-app
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-data
      volumes:
      - name: postgres-data
        emptyDir: {} 