apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres-service
  name: postgres-service
spec:
  type: ClusterIP
  ports:
  - name: "postgre-service"
    port: 5432
    targetPort: 5432
  selector:
    app: postgres-app