apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: library-app
  name: library-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: library-app
  template:
    metadata:
      labels:
        app: library-app
    spec:
      containers:
      - image: kabi123/library
        name: library-app
        envFrom:
        - configMapRef:
            name: configmap-lib
        volumeMounts:
        - name: library-longhorn-pvc
          mountPath: /myapp
        ports:
        - containerPort: 3000
          name: library-app
      volumes:
      - name: library-longhorn-pvc
        persistentVolumeClaim:
          claimName: library-longhorn-pvc