apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: library-app
  name: library-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: library-app
  template:
    metadata:
      labels:
        app: library-app
    spec:
      containers:
      - image: kabi123/library
        name: library-app
        envFrom:
        - configMapRef:
            name: configmap-lib
        ports:
        - containerPort: 3000
          name: library-app