kind: ConfigMap
apiVersion: v1
metadata:
  name: grafana-datasources
  namespace: monitoring
data:
  ds.yaml: |-

    {
        "apiVersion": 1,
        "datasources": [
            {
              "name": "test",
              "type": "prometheus",
              "url": "http://164.92.188.100:30536/"
            }
        ]
    }
