apiVersion: v1
kind: Service
metadata:
  labels:
    app: library-service
  name: library-service
spec:
  type: NodePort
  ports:
  - name: "library-service"
    port: 5000
    targetPort: 3000
    nodePort: 31000
  selector:
    app: library-app
  