apiVersion: v1
kind: Pod
metadata:
  name: jnlp-agent
spec:
  containers:
    - name: jnlp
      image: kabi123/inbound-agent-rails
      envFrom:
        - configMapRef:
            name: configmap-lib-test
      command:
        - "/usr/local/bin/jenkins-agent"
      tty: true
      volumeMounts:
        - name: kubeconfig-volume
          mountPath: /kubeconfig
          readOnly: true
        - name: docker-config
          mountPath: /kaniko/.docker
      securityContext:
        runAsUser: 0
        privileged: true
  restartPolicy: Never
  volumes:
    - name: kubeconfig-volume
      secret:
        secretName: kubeconfig-secret
    - name: docker-config
      projected:
        sources:
          - secret:
              name: dockercred
              items:
                - key: .dockerconfigjson
                  path: config.json
