apiVersion: v1
kind: Pod
metadata:
  name: jnlp-agent
spec:
  containers:
    - name: jnlp
      image: registry.digitalocean.com/devopsreg/inbound-agent-rails:1
      envFrom:
        - secretRef:
            name: database-secret  # Corrected indentation here
      command:
        - "/usr/local/bin/jenkins-agent"
      tty: true
      volumeMounts:
        - name: kubeconfig-volume
          mountPath: /kubeconfig
          readOnly: true
        - name: docker-config
          mountPath: /kaniko/.docker
      securityContext:
        runAsUser: 0
        privileged: true
  imagePullSecrets:
          - name: mycr
  restartPolicy: Never
  volumes:
    - name: kubeconfig-volume
      secret:
        secretName: kubeconfig-secret
    - name: docker-config
      projected:
        sources:
          - secret:
              name: docker-registry-secret
              items:
                - key: .dockerconfigjson
                  path: config.json
